[[task]]
  id = "sqlc"
  type = "short"
  watch = ["sqlc.yaml", "*.sql"]
  cmd = "go run github.com/sqlc-dev/sqlc/cmd/sqlc@latest generate"

[[task]]
  id = "dev"
  type = "long"
  dependencies = ["sqlc"]
