[[task]]
  id = "dev"
  type = "long"
  dependencies = ["templ"]

[[task]]
  id = "templ"
  type = "short"
  watch = ["*.templ"]
  cmd = "go run github.com/a-h/templ/cmd/templ generate ."

[[task]]
  id = "test"
  type = "short"
  dependencies = ["vulncheck", "staticcheck", "go-test", "vet"]

[[task]]
  id = "vulncheck"
  type = "short"
  cmd = "go run golang.org/x/vuln/cmd/govulncheck ./..."

[[task]]
  id = "staticcheck"
  type = "short"
  cmd = "go run honnef.co/go/tools/cmd/staticcheck ./..."

[[task]]
  id = "vet"
  type = "short"
  cmd = "go vet ./..."

[[task]]
  id = "go-test"
  type = "short"
  cmd = "go test ./..."
