// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Dataset struct {
	Name             string
	IsOnLocal        sql.NullBool
	LocalObservedAt  sql.NullInt64
	IsOnRemote       sql.NullBool
	RemoteObservedAt sql.NullInt64
}

type Snapshot struct {
	Dataset          string
	Name             string
	CreatedAt        int64
	IsOnLocal        sql.NullBool
	LocalObservedAt  sql.NullInt64
	IsOnRemote       sql.NullBool
	RemoteObservedAt sql.NullInt64
}
